### ISSUE TITLE
Fix: 아이템 생성 제한 시 오류 발생 버그 수정

### ISSUE THREAD

**Issue by andsosallycanwait** [HyeonjungYun/SaveTheEarthGame#51]
- 모든 아이템의 생성 개수 제한 시 오류가 발생함
- 에러는 다음과 같음

```
Traceback (most recent call last):
  File "c:\Users\andsosallycanwait00\Desktop\24-1\Open Source SW\team_project_team4\SaveTheEarth.py", line 637, in <module>
    game_play()
  File "c:\Users\andsosallycanwait00\Desktop\24-1\Open Source SW\team_project_team4\SaveTheEarth.py", line 554, in game_play
    items = [[i[0], i[1], i[2] + 3, i[3]] for i in items if i[2] < screen_height]
                                                            ~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by andsosallycanwait** [comment]
버그 해결 및 pull request 완료
